/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.Estudiantes;

import Controllers.CursosController;
import Controllers.UsuarioController;
import Helpers.CursosCBox;
import Helpers.ProfesoresCBox;
import Models.UsuarioModel;
import Views.CrearUsuario;
import Views.Rector.HomeRector;
import java.awt.event.ItemEvent;
import javax.swing.JFrame;

/**
 *
 * @author NEW PC MDMS
 */
public class VerEstudiantes extends javax.swing.JFrame {

    private int _estudiante_perfil_id = 3;

    /**
     * Creates new form VerEstudiantes
     */
    public VerEstudiantes() {
        initComponents();

        setTitle("Estudiantes");
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        UsuarioController controller = new UsuarioController();
        //OBTENER LOS USUARIOS CON EL PERFIL Y LLENAR TABLA
        controller.obtenerUsuariosPerfil(_estudiante_perfil_id, tblEstudiantes, 0);

        CursosController cursosController = new CursosController();
        cursosController.loadDataCBox(cbxCursos);
        
        cursosController.cargarProfesoresFiltro(cbxProfesores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();
        btnRegresarp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbxCursos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxProfesores = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEstudiantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEstudiantes);

        btnRegresarp.setText("REGRESAR");
        btnRegresarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarpActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ESTUDIANTES");

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel3.setText("* Para editar un registro haga click sobre el *");

        cbxCursos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCursosItemStateChanged(evt);
            }
        });

        jLabel2.setText("Filtrar Curso");

        cbxProfesores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxProfesoresItemStateChanged(evt);
            }
        });
        cbxProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProfesoresActionPerformed(evt);
            }
        });

        jLabel4.setText("Filtrar Profesor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresarp, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cbxProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(cbxCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresarp)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEstudiantesMouseClicked
        //INICIALIZAR VISTA
        CrearUsuario vwCrearUsuario = new CrearUsuario();
        vwCrearUsuario.setVisible(true);

        //INICIALIZAR CONTROLADOR
        UsuarioController controller = new UsuarioController();

        //BUSCAR EL USUARIO AL QUE SE LE DA CLICK
        UsuarioModel usuario = controller.buscarUsuario(tblEstudiantes);

        //MOSTRAR USUARIO EN FORMULARIO
        vwCrearUsuario.infoCampos(usuario, _estudiante_perfil_id, 2, tblEstudiantes, 0);
    }//GEN-LAST:event_tblEstudiantesMouseClicked

    private void btnRegresarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarpActionPerformed
        HomeRector hRecto = new HomeRector();
        hRecto.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarpActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        CrearUsuario vwCrearUsuario = new CrearUsuario();
        vwCrearUsuario.setVisible(true);
        vwCrearUsuario.infoCampos(null, _estudiante_perfil_id, 1, tblEstudiantes, 0);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cbxCursosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCursosItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            CursosCBox curso = (CursosCBox) cbxCursos.getSelectedItem();

            UsuarioController controller = new UsuarioController();
            controller.obtenerUsuariosPerfil(_estudiante_perfil_id, tblEstudiantes, curso.getId());

            ProfesoresCBox profeBox = new ProfesoresCBox(0, "Ninguno");
            cbxProfesores.setSelectedItem(profeBox);
        }
    }//GEN-LAST:event_cbxCursosItemStateChanged

    private void cbxProfesoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxProfesoresItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            ProfesoresCBox profe = (ProfesoresCBox) cbxProfesores.getSelectedItem();

            UsuarioController controller = new UsuarioController();

            if (profe.getId() == 0) {
                controller.obtenerUsuariosPerfil(_estudiante_perfil_id, tblEstudiantes, 0);
            } else {
                controller.obtenerEstudiantesProfesor(tblEstudiantes, profe.getId());
            }

            CursosCBox cursoBox = new CursosCBox(0, "Seleccione");
            cbxCursos.setSelectedItem(cursoBox);
        }
    }//GEN-LAST:event_cbxProfesoresItemStateChanged

    private void cbxProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProfesoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxProfesoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerEstudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnRegresarp;
    private javax.swing.JComboBox<String> cbxCursos;
    private javax.swing.JComboBox<String> cbxProfesores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblEstudiantes;
    // End of variables declaration//GEN-END:variables
}
